maven release prep
cedar-policy/cedar-java pull request #27
Opened 2023-07-14 22:48 UTC by andrewmwells-amazon

Preparation for maven release. Make CedarJavaFFI pull cedar from crates.io. Make relevant changes to testing.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-07-15 00:00 UTC, shaobo-he-aws approved these changes
LGTM.

2023-07-15 00:00 UTC, shaobo-he-aws commented on CedarJava/build.gradle
> +//  environment 'CEDAR_JAVA_FFI_LIB', 'set to absolute path of cedar_java_ffi native library (including file extension)'
Nit: indentation issue here.

2023-07-17 18:58 UTC, cdisselkoen commented on CedarJava/src/test/java/com/cedarpolicy/SharedIntegrationTests.java
> +        if(Files.notExists(Paths.get(CEDAR_INTEGRATION_TESTS_ROOT, "corpus_tests"))) {
+1

2023-07-17 18:59 UTC, cdisselkoen requested changes
Looks good except for the issue Shaobo pointed out in comments

2023-07-18 16:17 UTC, anwarmamat approved these changes

2023-07-18 17:20 UTC, andrewmwells-amazon commented on CedarJava/src/test/java/com/cedarpolicy/SharedIntegrationTests.java
> +        //If we can't find the `cedar` package, don't try to load integration tests.
Added `MUST_RUN_CEDAR_INTEGRATION_TESTS` env var to ensure we run tests in CI.

2023-07-18 17:20 UTC, andrewmwells-amazon commented on CedarJava/build.gradle
> +//  environment 'CEDAR_JAVA_FFI_LIB', 'set to absolute path of cedar_java_ffi native library (including file extension)'
Decided to leave as reminder

2023-07-18 17:21 UTC, andrewmwells-amazon commented on CedarJava/src/test/java/com/cedarpolicy/SharedIntegrationTests.java
> +        if(Files.notExists(Paths.get(CEDAR_INTEGRATION_TESTS_ROOT, "corpus_tests"))) {
Added `MUST_RUN_CEDAR_INTEGRATION_TESTS` to ensure tests are run in CI.

2023-07-18 17:23 UTC, andrewmwells-amazon commented on CedarJava/src/main/java/com/cedarpolicy/AuthorizationEngine.java
> +        return "2.3";
Leaving as-is for now.

2023-07-18 17:24 UTC, cdisselkoen approved these changes

2023-07-18 18:07 UTC, merged